### ISSUE TITLE
Add barèmes values to parameters v2

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-web-api#107]
In #100, we added support for legislation “simple” parameters. We now need to also find a representation for “barème” values.

**Comment by fpagnoux** [comment]
## Definition

To be clear, let's explicit what we mean by a bareme in OpenFisca.

A bareme is a more sophisticated version of a basic rate. It is usually used to compute contributions, for instance income tax or social security contribution. The most typical example is the French income tax.

The basis (_l'assiette_) is divided in slices (_tranches_), according to a list of thresholds (_seuils_). A marginal rate is defined for each slice.

If the rates grow with the thresholds, it's a progressive contribution, but that's not always the case.

## Naming

Our first topic will be to find a name for this, as bareme doesn't work in English. The most common translation is **marginal tax scale**, but what it seems to assume we're talking about taxes, which may not be the case (social contributions are not taxes).

The best I found is **marginal scale**, but I'm not sure it's really spread.

## Marginal scale vs simple parameter

To distinguish a simple parameter from a marginal scale, we can:

- Add a `type` property to the root object (see examples below)
- Add a differently named property to the root object. `structure` ?
- Add no property and rely on the data structure (won't scale when we introduce a new type of parameter).

## Representation

I can see two ways to represent a bareme, whether we factorise by date or following the bareme structure.

### Proposition 1 : by date

```JSON
{
    "description": "Tranches de l'IR",
    "id": "impot_revenu.bareme",
    "type": "marginalScale"
    "values": {
        "2015-01-01": {
            "9700": 0.14,
            "26791": 0.3,
            "71826": 0.41
        }, "2014-01-01": {
            "9690": 0.14,
            "26764": 0.3,
            "71754": 0.41
        }
        }, "2013-01-01": {
            "6011": 0.055,
            "11991": 0.14,
            "26631": 0.3,
            "71397": 0.41
        }
    }
}
```

Advantages:
  - Compact
  - Close to the ["simple" bareme representation](https://api.ir.openfisca.fr/parameter/cotsoc.gen.smic_h_b)


### Proposition 2 : following the slices structure

```JSON
{
    "description": "Tranches de l'IR",
    "id": "impot_revenu.bareme",
    "type": "marginalScale"
    "values": [
        {
            "threshold": {
                "2015-01-01": 9700,
                "2014-01-01": 9690,
                "2013-01-01": 6011,
            },
            "rate": {
                "2014-01-01": 0.14,
                "2013-01-01": 0.055
            },
        }, {
            "threshold": {
                "2015-01-01": 26791,
                "2014-01-01": 26764,
                "2013-01-01": 11991,
            },
            "rate": {
                "2014-01-01": 0.3,
                "2013-01-01": 0.14
            },
        } {
            "threshold": {
                "2015-01-01": 71826,
                "2014-01-01": 71754,
                "2013-01-01": 26631,
            },
            "rate": {
                "2014-01-01": 0.41,
                "2013-01-01": 0.3
            }
        }, {
            "threshold": {
                "2014-01-01": null,
                "2013-01-01": 71397,
            },
            "rate": {
                "2014-01-01": null,
                "2013-01-01": 0.41
            }
        }
    ]
}
```


Advantage:
  - If one threshold/rate change, we just have one line to add, instead of a full date block.
    - From what I saw, this case doesn't seem to happen so often

**Comment by fpagnoux** [comment]
I'm clearly more leaning towards proposition 1. @cbenz @MattiSG your feedback is welcome on 
- Proposition 1 vs propositon 2
- How do we name the concept ?
- What's should be the name of the property (if there is one) ?

**Comment by cbenz** [comment]
I like proposition 1 for its compactness.

About the naming, "marginal scale" seems good to me – better than "marginal tax scale" since it probably can be used for something else than a tax. By the way it's already used in [`taxscales.py`](https://github.com/openfisca/openfisca-core/blob/ff4e04e4c183b41fadbcc8a90169cd4c14ecec49/openfisca_core/taxscales.py#L185), but there are other names too and I'm not sure which does what. @benjello is better to answer.

Next, if I remember correctly, there is a need to track the brackets (tranche in French) which can disappear at some point in time. @benjello can you confirm?

**Comment by benjello** [comment]
The bracket was the sum of threshold, a rate and possibly assiette. I think that the later is no more used at all but that should be checked. A bracket can be easily understood as an item of representation 1.

**Comment by MattiSG** [comment]
First of all, thanks @fpagnoux for this thorough research and clear suggestion. We are getting closer to RFCs, and that makes me proud of our team 😊

Now, on to the proposition.

- - - -

## Critique of solution 2

Needlessly complex, as others have already stated.

## Critique of solution 1

I'm not in favour of this `type` property that changes how you're supposed to handle `values`. If you want clients to make disjunctions, then just use a different property 🙂 We could thus have either a `values` property or a `scale` property, and the type is inferred through the presence of one or the other.

Think about the client code:

(solution 1)
```js
if (response.type == 'marginalScale')
    value = response.values[date][threshold];
else
    value = response.values[date];
```

vs

(solution 3)
```js
if (response.scale)
    value = response.scale[date][threshold];
else
    value = response.values[date];
```

Using different properties scales as much, but doesn't induce repetition, makes introspection easier since navigation algorithms will fail early (`"values" is not a property` instead of `Number is not an Object`), and decreases human cognitive load (the root property name defines how to interpret the data structure).

I'm still worried that the interpretation of the thresholds is not obvious in the representation proposed in solution 1: is is the lower or the upper bound? Is it inclusive or exclusive?

Solution: guarantee that there is always a lower bound. In the `impot_revenu` example, that would mean that the `0: 0` pair is present. The responsibility is thus moved towards the legislation, but looking at [`param.xml`](https://github.com/openfisca/openfisca-france/blob/5f9a3cf837e3fb68421ae6609f38d489804fff9e/openfisca_france/param/param.xml) it looks like this is already the case.

Thus:

## Proposition 3

```json
{
    "description": "Tranches de l'impôt sur le revenu",
    "id": "impot_revenu.bareme",
    "scale": {
        "2015-01-01": {
            "0": 0,
            "9700": 0.14,
            "26791": 0.3,
            "71826": 0.41
        }, "2014-01-01": {
            "0": 0,
            "9690": 0.14,
            "26764": 0.3,
            "71754": 0.41
        }, "2013-01-01": {
            "0": 0,
            "6011": 0.055,
            "11991": 0.14,
            "26631": 0.3,
            "71397": 0.41
        }
    }
}
```

## Additional questions

Are there any scales that are _not_ defining only a map where keys are [infimi](https://en.wikipedia.org/wiki/Infimum_and_supremum), i.e. whose thresholds are not **ascending** and **inclusive**? I didn't see any in looking at `param.xml`, but if that can happen (example: thresholds triggered by deficit, where thresholds would thus be [supremi](https://en.wikipedia.org/wiki/Infimum_and_supremum)), then the interpretation is more ambiguous and could mean needing to introduce either a set of different properties such as `ascendingScale`, `descendingScale`, or some metadata.

If this could only theoretically happen, but is not known and seems unlikely, then we can proceed with `scale` and introduce `descendingScale` when the need arises.

**Comment by MattiSG** [comment]
## Proposition 4

Actually, for a “simple parameter”, the property is… `values`. Indeed, the _simple parameter_ **has** _values_, it **is** not only values!

Similarly, shouldn't a _scale_ **have** _thresholds_ rather than **being** a _scale_? Thus:

```json
{
    "description": "Tranches de l'impôt sur le revenu",
    "id": "impot_revenu.bareme",
    "thresholds": {
        "2015-01-01": {
            "0": 0,
            "9700": 0.14,
            "26791": 0.3,
            "71826": 0.41
        }, "2014-01-01": {
            "0": 0,
            "9690": 0.14,
            "26764": 0.3,
            "71754": 0.41
        }, "2013-01-01": {
            "0": 0,
            "6011": 0.055,
            "11991": 0.14,
            "26631": 0.3,
            "71397": 0.41
        }
    }
}
```

**Comment by fpagnoux** [comment]
The `thresholds` are just the left parts of the objects. The equivalent of `values` would be `brackets`.

## Proposition 5

```json
{
    "description": "Tranches de l'impôt sur le revenu",
    "id": "impot_revenu.bareme",
    "brackets": {
        "2015-01-01": {
            "0": 0,
            "9700": 0.14,
            "26791": 0.3,
            "71826": 0.41
        }, "2014-01-01": {
            "0": 0,
            "9690": 0.14,
            "26764": 0.3,
            "71754": 0.41
        }, "2013-01-01": {
            "0": 0,
            "6011": 0.055,
            "11991": 0.14,
            "26631": 0.3,
            "71397": 0.41
        }
    }
}
```

**Comment by fpagnoux** [comment]
The only drawback I can see using `has` vs `is` is that the only way we can differentiate two types of parameters is by their properties, which may be similar.

For instance, we can think about a kind of school scholarship. If you make less than `10000`, you get `20%` of the some constants (like `bmaf` in France), if you make less than `15000`, you get `10%`, etc. This is also a **threshold** mechanism. A JSON representation would be:

{
    "description": "Bourse de collège",
    "id": "education.bourse.bareme",
    "thresholds": {
        "2015-01-01": {
            "0": 0.2,
            "10000": 0.1,
            "15000": 0.05,
            "20000": 0
        }
    }
}

This may be confusing, because as a client:
- When I see this, I only know that this parameter have thresholds.
- I could imagine that it's a marginal scale, as marginal scale also have thresholds.
- I can understand precisely **only** if I know that, by convention, a marginal scale **is** a parameter with **brackets**, that a simple threshold mechanism **is** a parameter with **thresholds**. 

This can be even more tricky if two parameters types end up having **exactly** the same property. For instance if some kind of mechanism is a non-marginal tax scale (you make less than 10000, you pay 5%, you make more, you pay 10% of your global income). This kind of mechanism would have **brackets** too, but would be different than the previous one.

**Comment by fpagnoux** [comment]
I'm moving on implementing proposition 3 (as its concurrent 5 only differs by the name of a property), but let's keep discussing ;)

**Comment by benjello** [comment]
I am for proposition 5.

**Comment by benjello** [comment]
It should be extended to different type of tax scales though. You have average rate tax scales (the average rate varies linearly between two values in a bracket), constant amount tax scale too (the amount you pay is constant in a bracket).

**Comment by MattiSG** [comment]
I back proposition 5.

The variants in interpretation put forward by @benjello can be added later, either as an additional property or as a variant in the `brackets` property name.

@benjello do you have examples of each type that would already be declared as OpenFisca parameters?

**Comment by cbenz** [comment]
I'm OK for proposition 5. We'll be able to add a new `bracketType` property, or change the content of `bracket`, if a new kind of scale appears.

**Comment by fpagnoux** [comment]
Thanks all for backing up the solution I implemented 😁 !

**Comment by benjello** [comment]
@MattiSG there is such a constant mount bareme [here](https://github.com/openfisca/openfisca-tunisia/blob/master/openfisca_tunisia/param/param.xml#L1014-L1095) (not used in a fromula yet IIRC).
The average tax-rate bareme is used in the [Landais-Piketty-Saez reform](https://github.com/openfisca/openfisca-france/blob/5f9a3cf837e3fb68421ae6609f38d489804fff9e/openfisca_france/reforms/landais_piketty_saez.py#L80-L115)
