### ISSUE TITLE
Document API routes

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-web-api#72]

**Comment by cbenz** [comment]
Cf https://github.com/openfisca/openfisca-gitbook/commit/65a680cabbb50b7656e8858d26685b9014c8c72e

There are no more TODOs in https://doc.openfisca.fr/openfisca-web-api/endpoints.html

I removed the deprecated features.

**Comment by fpagnoux** [comment]
Nice, thanks @cbenz !

Can we thus close the issue ?

**Comment by cbenz** [comment]
@fpagnoux Did you find it useful for a newcomer?

I did not put as much details as I would have liked to describe the output of the `entities` endpoint.
There are many cases, roles, subroles, max counts, which I think are understood by mastering the concept of entity.

I close this issue because it was about documenting the endpoints, but I'm OK to open new ones later.

**Comment by fpagnoux** [comment]
I think it was the good level of investment.

It brings information that is useful to the users, and help them figure out which route they should use. I'm sure we could do better, but I would only do after rethinking the api routes.
